apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "47"
  creationTimestamp: "2024-02-22T15:42:51Z"
  generation: 48
  name: nodejs-app
  namespace: default
  resourceVersion: "11506962"
  uid: 7b78e8a6-2433-496d-ade9-09c1146d8bec
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodejs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs
    spec:
      containers:
      - env:
        - name: PGUSER
          value: ps_user
        - name: PGHOST
          value: postgres
        - name: PGDATABASE
          value: postgres
        - name: PGPASSWORD
          value: PASSWORD_GOES_HERE
        - name: PGPORT
          value: "5432"
        - name: REACT_APP_GMAPS
          value: KEY_GOES_HERE
        - name: STRIPE_PUBLIC_KEY
          value: KEY_GOES_HERE
        - name: STRIPE_SECRET_KEY
          value: KEY_GOES_HERE
        - name: EMAIL_USER
          value: geogalavant@zohomail.com
        - name: EMAIL_PASSWORD
          value: PASSWORD_GOES_HERE
        image: vhafener/geogalavant:v4.1
        imagePullPolicy: Always
        name: geogalavant
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
