apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nodejs-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":3000}],"selector":{"app":"nodejs"},"type":"NodePort"}}
  creationTimestamp: "2024-02-22T19:36:41Z"
  name: nodejs-service
  namespace: default
  resourceVersion: "5902001"
  uid: 3eb183a3-d3e5-4438-9c40-98e7cee5dc3e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.112.230
  clusterIPs:
  - 10.105.112.230
  externalIPs:
  - 129.21.49.84
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 129.21.49.84
  ports:
  - nodePort: 31877
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodejs
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
